pipeline {
    agent any
    tools {
        maven 'Maven3'
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build auth-service') {
            steps {
                dir('auth-service') {
                sh 'mvn clean package -DskipTests'
            }
            }
        }
    }
}
