pipeline {
    agent any
    tools {
        maven 'Maven3'
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build job-service') {
            steps {
                dir('spring-boot-microservices-main/job-service') {
                    sh 'mvn clean compile'
                }
            }
        }
        stage('Unit Tests') {
            steps {
                dir('spring-boot-microservices-main/job-service') {
                    sh 'mvn test'
                }
            }
            post {
                always {
                    junit '**/target/surefire-reports/*.xml'
                }
            }
        }
        stage('Integration Tests') {
            steps {
                dir('spring-boot-microservices-main/job-service') {
                    sh 'mvn verify'
                }
            }
            post {
                always {
                    junit '**/target/failsafe-reports/*.xml'
                }
            }
        }
        stage('Package') {
            steps {
                dir('spring-boot-microservices-main/job-service') {
                    sh 'mvn package -DskipTests'
                }
            }
        }
    }
    post {
        always {
            cleanWs()
        }
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}