apiVersion: apps/v1
kind: Deployment
metadata:
  name: camunda-service
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camunda-service
  template:
    metadata:
      labels:
        app: camunda-service
    spec:
      containers:
      - name: camunda-service
        image: camunda-service-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "default"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://eureka-server:8761/eureka/"
        - name: SPRING_CLOUD_CONFIG_ENABLED
          value: "false"
        - name: SPRING_CONFIG_IMPORT
          value: "optional:configserver:http://config-server:8888/"
        resources:
          limits:
            cpu: "0.7"
            memory: "1Gi"
          requests:
            cpu: "0.3"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 15
