apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: microservices
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    scrape_configs:
      - job_name: 'eureka-server'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['eureka-server:8761']
      
      - job_name: 'gateway'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['gateway:8080']
      
      - job_name: 'auth-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['auth-service:9898']
      
      - job_name: 'user-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['user-service:9090']
      
      - job_name: 'camunda-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['camunda-service:8080']
