pipeline {
    agent any
    tools {
        nodejs 'Node20'
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build camunda_front_bpmn') {
            steps {
                dir('camunda_front_bpmn') {
                    sh 'npm install'
                    sh 'npm run build'
                }
            }
        }
    }
    post {
        always {
            cleanWs()
        }
        success {
            echo 'Frontend build completed successfully!'
        }
        failure {
            echo 'Frontend build failed!'
        }
    }
}
