apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: microservices
  labels:
    app: auth-service
spec:
  selector:
    app: auth-service
  ports:
  - port: 9898
    targetPort: 9898
  type: ClusterIP
