apiVersion: v1
kind: Service
metadata:
  name: camunda-service-external
  namespace: microservices
  labels:
    app: camunda-service
spec:
  selector:
    app: camunda-service
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30081
  type: NodePort
