apiVersion: v1
kind: Service
metadata:
  name: eureka-server-external
  namespace: microservices
  labels:
    app: eureka-server
spec:
  selector:
    app: eureka-server
  ports:
  - port: 8761
    targetPort: 8761
    nodePort: 30761
  type: NodePort
