apiVersion: v1
kind: Service
metadata:
  name: gateway-external
  namespace: microservices
  labels:
    app: gateway
spec:
  selector:
    app: gateway
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
  type: NodePort
