pipeline {
    agent any
    tools {
        maven 'Maven3'
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build user-service') {
            steps {
                sh 'mvn clean package -DskipTests'
            }
        }
    }
}
