apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: eureka-server-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: eureka-server
  endpoints:
  - port: web
    path: /actuator/prometheus
    interval: 15s
