apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  labels:
    app: eureka-server
spec:
  selector:
    app: eureka-server
  ports:
  - port: 8761
    targetPort: 8761
    name: web
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server-nodeport
  labels:
    app: eureka-server
spec:
  selector:
    app: eureka-server
  ports:
  - port: 8761
    targetPort: 8761
    nodePort: 30761
    name: web
  type: NodePort
